### ISSUE TITLE
Very dark screen (very low Gamma) in Fullscreen mode by default 

### ISSUE THREAD

**Issue by q4a** [opennox/opennox#471]
When I first time started game and enable Fullscreen mode I got very dark screen.

System: Ubuntu 20.04 amd64
GPU: GT 730 + proprietary driver 470.103.01
Game builded from source on https://github.com/noxworld-dev/opennox/commit/c59eea01ab3a3618b279767c15e3c00376b08a81

Compare Windowed mode:
![windowed](https://user-images.githubusercontent.com/1950719/162619079-21b94ec3-3039-4ef1-98a3-685003565c8a.jpg)

And Fullscreen mode:
![fullscreen](https://user-images.githubusercontent.com/1950719/162619121-fc63b766-b83c-42b1-be92-530ef7037d63.jpg)

This can be "fixed" with simple changing Gamma.
It is a bit strange when for me: Gamma is changing your monitor settings, not just game screen.

**Comment by dennwc** [comment]
Might be related to https://github.com/noxworld-dev/opennox/issues/416

**Comment by mozo78** [comment]
Same problem on Arch Linux.

**Comment by dennwc** [comment]
We probably don't convert old gamma value from the config correctly :thinking:

**Comment by Evengard** [comment]
...We probably should recalculate it from the old format in the internal representation and back on each config load/save, we probably shouldn't pollute the original CFG files with different settings than the original game.

**Comment by dennwc** [comment]
Agree. The `Gamma2` was introduced in the WASM version and we just never revisited it.
