### ISSUE TITLE
opennox host quest has no ping response, while opennox-server is fine [SOLVED]

### ISSUE THREAD

**Issue by scheckley** [opennox/opennox#475]
under Linux, opennox multiplayer host quest results in no ping response from the host. opennox-server is listed in multiplayer with ping response on the same machine.  I don't understand why opennox multiplayer and opennox-server are different.

**Comment by Evengard** [comment]
You don't run them simultaneously, do you?

**Comment by scheckley** [comment]
no, i tried opennox-server separately after having problems connecting to games hosted in opennox

**Comment by scheckley** [comment]
solved - iptables issue.  Adding the following rules in addition to opening port 18590 has enabled ping and client connection.  I don't think all of these are needed. I also had to enable UPnP in my router config.

-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
