### ISSUE TITLE
AppImage package

### ISSUE THREAD

**Issue by dennwc** [opennox/opennox#478]
Alternatively to Flatpak package (#477) we could provide AppImage. One of the users already contributed a mostly complete config to build it, we now need to integrate it into the build process.

**Comment by dennwc** [comment]
Here's the prototype contributed by Xandros:
[OpenNox-AppImageDeployer-1.zip](https://github.com/noxworld-dev/opennox/files/8500331/OpenNox-AppImageDeployer-1.zip)

Ideally we would need to pull all OpenNox system dependencies into AppImage as well, ideally from our Docker build.

**Comment by dennwc** [comment]
@XandrosDarkstorm would be great if you could finish it, when you have time :)

**Comment by XandrosDarkstorm** [comment]
@dennwc Please clarify what needs to be done. It should be ready for usage (it even has documentation).

**Comment by dennwc** [comment]
It needs to be added to our [release workflow](https://github.com/noxworld-dev/opennox/blob/dev/.github/workflows/build-and-release.yml) so that AppImage files appear on new releases going forward.

**Comment by XandrosDarkstorm** [comment]
@dennwc Ah. You want direct Github integration, right? I never worked with Github's workflow feature. Can you contact me and describe a little how this should be done. I'll be glad to make changes.

**Comment by XandrosDarkstorm** [comment]
I have opened PRs for official implementation:
[https://github.com/noxworld-dev/build-docker/pull/1](https://github.com/noxworld-dev/build-docker/pull/1)
[https://github.com/noxworld-dev/opennox/pull/603](https://github.com/noxworld-dev/opennox/pull/603)

After the merge, i can continue providing support for these builds, if needed.

**Comment by XandrosDarkstorm** [comment]
AppImage package is now provided since version [v1.8.12-alpha9](https://github.com/noxworld-dev/opennox/releases/tag/v1.8.12-alpha9). Documentation for the AppImage release of OpenNox will be provided soon.
