### ISSUE TITLE
Abnormal color in observer mode.

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#484]
![img](https://user-images.githubusercontent.com/16138767/171830491-4d3ad563-a4bf-499d-86ab-8da75f926313.png)

When I set the observer mode in the options, the character's color changes strangely.

**Comment by Evengard** [comment]
Hrm, the character should look translusive. Does the same happens when casting the invisibility spell?

**Comment by hjyoon** [comment]
It didn't happen with the use of the invisibility spell.
