### ISSUE TITLE
Minimap walls are not being displayed properly on campaign 

### ISSUE THREAD

**Issue by klnmhjvb** [opennox/opennox#485]
![OpenNox v1 8 10 2022-06-04 오전 12_28_31](https://user-images.githubusercontent.com/88615739/171885393-2bbf065e-8be7-4d81-a753-86806faf5e0f.png)

**Comment by klnmhjvb** [comment]
All walls are displayed broken

**Comment by Evengard** [comment]
Wait, isn't it because of the vision absence? That's probably not a bug then, the minimap doesn't show what you never saw in the campaign.

**Comment by klnmhjvb** [comment]
unfortunately its not about vision, and minimap shows all the walls basically if the area has been explored. All L shaped walls are displayed broken

**Comment by klnmhjvb** [comment]
I think it didnt happen on former version

**Comment by dennwc** [comment]
I definitely see some weird wall borders on the screenshot, it's almost certainly because of the rewritten pixel/line renderer.
