### ISSUE TITLE
The effect when the barrel explodes is different from vanilla.

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#494]
vanilla:
![vanilla](https://user-images.githubusercontent.com/16138767/173259056-5dace8d9-4875-4571-ad32-5ea4bdac8619.gif)

opennox:
![opennox](https://user-images.githubusercontent.com/16138767/173259054-575b8d36-7c91-45f6-b876-b731c70e76e3.gif)

**Comment by dennwc** [comment]
You mean that only one barrel explodes? Could you try it on commit fc91de6c?

**Comment by hjyoon** [comment]
> You mean that only one barrel explodes? Could you try it on commit [fc91de6](https://github.com/noxworld-dev/opennox/commit/fc91de6c637f471a90b37070a39682dd98aec9c0)?

It seems to have been fixed in fc91de6
