### ISSUE TITLE
Error loading vanilla savefile

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#511]
I tried loading the save file (War01a map file).
The save file is a map saved by vanilla.
[SAVE0001.zip](https://github.com/noxworld-dev/opennox/files/9175774/SAVE0001.zip)
![vanilla9](https://user-images.githubusercontent.com/16138767/180646962-403bc2cc-c8d9-439a-b5b7-44202820ba95.gif)

**Comment by melissis** [comment]
I also have a fail on loading savefile (looks the same as in gif). The file was made by OpenNox. It works if I open it in vanilla, but not in OpenNox.
Field of Valor, just after the last cutscene with the necromancer.
[v1.8.11](https://github.com/noxworld-dev/opennox/releases/tag/v1.8.11)
[SAVE0013 bug melissis.zip](https://github.com/noxworld-dev/opennox/files/9848385/SAVE0013.bug.melissis.zip)

**Comment by dennwc** [comment]
Reopening to check.

**Comment by KILAH4716** [comment]
Issue #544 goes into greater detail as to how and why this bug occurs.

**Comment by dennwc** [comment]
Confirmed, works in upcomming alpha version.
