### ISSUE TITLE
HDR compatibility with SpecialK

### ISSUE THREAD

**Issue by Sawtaytoes** [opennox/opennox#522]
I was trying to add HDR to Nox using SpecialK. I followed the instructions which include adding `dgVoodoo` as a plugin and adding `ddraw.dll` or `d3d8.dll` to the game's root.

Didn't Nox come with DX7 originally? Did the renderer change?

If I remove the existing `ddraw.dll` from the folder, the old `Nox.exe` no longer works, but `opennox.exe` still works. This makes me think it's maybe updated to DX9 or changed it to OpenGL.

**Comment by Sawtaytoes** [comment]
I got it to work by naming `SpecialK32.dll` to `opengl32.dll`.

A few things surprised me:
1. The game runs at 30 fps. All these years, I had no clue.
2. The game looks awful and completely washed out in HDR :(.

**Comment by Evengard** [comment]
About the FPS you can read more here my explanations: https://github.com/noxworld-dev/opennox/issues/515
And yes, OpenNox uses SDL which in turns uses OpenGL for the actual drawing, instead of DirectDraw like back in the days.
