### ISSUE TITLE
Build fails on Arch Linux. Invalid value for -gcflags.

### ISSUE THREAD

**Issue by gennarocc** [opennox/opennox#523]
I was able to build this in the past but ran into issues when trying today. Is it possible I didn't install the correct dependencies ? 

```
$ go run ./internal/noxbuild                                                                                
+ go build -v -ldflags=-X 'github.com/noxworld-dev/opennox/v1/internal/version.commit=6acda8a3' -X 'github.com/noxworld-dev/opennox/v1/internal/version.version=v1.8.x' -gcflags="-trimpath=/home/gcc/Workspace/opennox/src" -asmflags="-trimpath=/home/gcc/Workspace/opennox/src" -o opennox ./cmd/opennox
invalid value "\"-trimpath=/home/gcc/Workspace/opennox/src\"" for flag -gcflags: parameter may not start with quote character "
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
exit status 2
exit status 1
```

**Comment by dennwc** [comment]
We need more info to debug this, namely:
1. What shell are you using? Is it `zsh`?
2. `go version`

**Comment by dennwc** [comment]
If you just want it to build for now, you could try commenting out [those lines](https://github.com/noxworld-dev/opennox/blob/dev/src/internal/noxbuild/main.go#L133) with `-gcflags` and `-asmflags`, they are only cosmetic.

**Comment by gennarocc** [comment]
Go Version
`go version go1.19.1 linux/amd64`

I commented out those lines and the build ran fine. Thank you.
