### ISSUE TITLE
Game stuck while running script

### ISSUE THREAD

**Issue by blmarket** [opennox/opennox#546]
[SAVE0011.tar.gz](https://github.com/noxworld-dev/opennox/files/9792102/SAVE0011.tar.gz)

Action: Enter the door

Expected result in Vanilla Nox: move to a new location
Actual Result in OpenNox: Game stuck with infinite loop of undefined builtin functions

Checked latest dev branch, pure_c_latest tag (dated 2022-Apr), and both failed.

**Comment by blmarket** [comment]
To handle this issue, seems I need to know how map executes script (e.g. hopefully the  script can be formatted in somewhat readable form, so I can understand what it does). Going to play around a bit. Any references around map script execution might be helpful.

**Comment by dennwc** [comment]
First, I would strongly recommend trying our E2E test automation to make reproducing faster. I'll write a piece of doc later as well.

You can record inputs passed to the game with:
```bash
NOX_E2E_RECORD=/some/path/recording.yml opennox
```
The game will run a bit faster, and will record all your actions. As soon as you close the game it will save this recording.

The, you can quickly replay it to see if bug reproduces on different commit:
```bash
NOX_E2E=/some/path/recording.yml opennox
```

This should help a lot with bisecting to find problematic commit faster.

Apart from it, you could automate it further by adding a [screen](https://github.com/noxworld-dev/opennox-e2e#screen) directive to the recording file (manually). You will first need to find a good version of OpenNox (just try recent release from newest to oldest), generate recording with it, place `screen` command at a moment which shows that map switched successfully. Then run that script with `git bisect run` and it will locate the version which changes that screenshot.

As for the formatting, the [map editor](https://github.com/pogonomic/MapEditor) could do that, I think. But it doesn't run well on Linux. Also I found a cleaner reconstruction of [script sources](https://github.com/noxworld-dev/opennox/files/9793903/nox-maps-decomp-scripts.zip) somewhere. Hope this helps.

**Comment by blmarket** [comment]
Still working on it - Found a commit which cause break: https://github.com/noxworld-dev/opennox/commit/6d7271d76e900819a3613af883395bb2baa9056b

**Comment by blmarket** [comment]
Seems it was a false alarm - I had "war03a.map" and "War03a.map" (case sensitive) where lowercased one was not a vanilla game map which cannot be loaded from OpenNox. Above commit had this line : https://github.com/noxworld-dev/opennox/commit/6d7271d76e900819a3613af883395bb2baa9056b#diff-98feba101f5edffb2dcaf8fa3599d23168eb259f99f68eb1f7299c5f8b4c4238R662
which is different from C code logic.
