### ISSUE TITLE
opennox-linux: dates of saves

### ISSUE THREAD

**Issue by amty** [opennox/opennox#555]
Hi.

In a "save/load game" dialog OpenNox on linux does something strange with dates.
```
$ ls -ld Save/SAVE0012/
drwxr-xr-x 18 amty users 4096 Nov 10 19:57 Save/SAVE0012/
```

But in the dialog the date is shown as "22-10-10, 19:57". I saved game into this slot multiple times, the date changes as on files so in a dialog, but the mismatch between "Nov" and 10 remains. Other saves (generated not by opennox-linux, but either by the original Nox.exe, or by opennox for windows run under wine) are ok. They were made in November and they are shown as 22-11-xx.

**Comment by txtsd** [comment]
My saves consistently have a -1 month offset. Today's (23-01-04) saves show as 22-12-04.
