### ISSUE TITLE
No sound effect when weapon collides with a wall

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#557]

**Comment by KILAH4716** [comment]
Is it possible we can get an example of when this occurs? This immediately sounds like a polygon issue within specific maps with no context.

**Comment by hjyoon** [comment]
> Is it possible we can get an example of when this occurs? This immediately sounds like a polygon issue within specific maps with no context.

Simple. It's just about the sound effect that appears when the player attacks the wall.

**Comment by dennwc** [comment]
Can confirm, there's just no hit sound in the latest dev version.

**Comment by dennwc** [comment]
Fixed on latest `dev`.
