### ISSUE TITLE
A skull object do not appear properly in Warrior Chapter 2

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#559]
![image](https://user-images.githubusercontent.com/16138767/203116349-a242b303-8649-487a-863c-746da9d0345b.png)

**Comment by dennwc** [comment]
Hmm, weird, can't reproduce on either 2f6abe4258553e07ec92fcc56bbe3b4e6159fb17, nor on the latest. What did you do exactly to trigger it?
