### ISSUE TITLE
Frog's HP is abnormal

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#560]
- the same for rats, both must have hp equal to 1

![image](https://user-images.githubusercontent.com/16138767/203117461-0c4c2dbc-413a-4559-9d8e-1d36f8376640.png)

**Comment by dennwc** [comment]
It's super weird, but I cannot confirm it either :thinking: Spawning new units correctly shows 1 hp.

**Comment by Evengard** [comment]
Maybe he have edited bin files, not original ones...

**Comment by ghost-redbrick** [comment]
hmm... OK I'll check again
