### ISSUE TITLE
The defensive posture using the shield is abnormal.

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#561]
![image](https://user-images.githubusercontent.com/16138767/203119429-1cc1eacb-65ab-462a-8106-537f77c91c1b.png)

**Comment by blmarket** [comment]
Bisect shows: 

First broken: https://github.com/noxworld-dev/opennox/commit/bd04334c8674a091a997c017bf8626856bc753b6
Last working: one previous of first broken - https://github.com/noxworld-dev/opennox/commit/fbfe4ab0af102962fef696123c00ea3a581e6c3d

**Comment by blmarket** [comment]
Please assign this to me (and maybe #562 as well)

**Comment by blmarket** [comment]
#567 was merged, which fixes this issue - in the latest dev branch.
Hmm... I have no permission to close this issue though ... is there someone?
