### ISSUE TITLE
The defensive posture using the staff is abnormal.

### ISSUE THREAD

**Issue by hjyoon** [opennox/opennox#562]
![image](https://user-images.githubusercontent.com/16138767/203120005-3e3298b1-0012-4310-bce7-16b41d800337.png)

**Comment by dennwc** [comment]
Could you please explain what is wrong here?

**Comment by hjyoon** [comment]
Certain types of attacks can be defended using the staff, which takes a defensive stance.
Here, the defense succeeds and takes no damage, but does not pose.

**Comment by blmarket** [comment]
I believe this should be fixed by #567 as well.
