### ISSUE TITLE
OpenNox Hates Invisibility

### ISSUE THREAD

**Issue by KILAH4716** [opennox/opennox#566]
This issue might have a direct tie with issue #544, but #544 also has a crashing issue if you attempt to load from OpenNox if you saved in Reloaded.

This issue revolves almost entirely around Invisibility. If you cast Invisibility, save, and load, you'll get a million different side effects, and I can't detect a pattern of what side effects you may or may not get, but Freeze, Force Field and Death are three possible effects. At this point, you can save and load to get rid of all effects because Force Field is also one of them, so OpenNox thinks that all this came from Invisibility, and Force Field gets shut down when you reload, so all effects also shut down. (You NEED to do this to remove the Freeze effect preventing you from moving.) The problem is if you have Death, Death bypasses Force Field and Invulnerability (another possible side effect), and you die immediately upon reloading, making that save unplayable.

Meanwhile, in Reloaded, if you cast Invisibility and save, when you reload, you're still invisible, and nothing crazy happens.

If I save while Invisible in Reloaded and load in OpenNox, I get a million side effects.

If I save while Invisible in OpenNox and load in Reloaded, I lose my invisibility.

If I save while having a million side effects, though, those side effects carry over to whatever version of Nox I'm playing, no matter if it's Reloaded or OpenNox.

https://www.youtube.com/watch?v=v6uK1y6Pm8k

**Comment by dennwc** [comment]
Oh wow. This is critical.

**Comment by dennwc** [comment]
Was unable to reproduce on latest `dev`. It means that either it's already fixed or something is very wrong with Windows build.

**Comment by KILAH4716** [comment]
When the latest version is released, I'll test it again.

**Comment by KILAH4716** [comment]
When the latest version is released, I'll test it again.

However, there's an update to #544 again directly tied to this issue I just discovered.

**Comment by dennwc** [comment]
Already fixed, so closing.
