### ISSUE TITLE
View Raw Speed Stat

### ISSUE THREAD

**Issue by KILAH4716** [opennox/opennox#580]
Paperjack and I have decisively concluded that the speed stat is a very complex stat to calculate. So to get some clarity on how speed is calculated and how it works, paperjack wants to display the speed percentage AND the raw stat in the stats menu. If you can't do that, then make a console command that allows us to display the current speed stat, including alterations with speed enchantments, Haste and Slow.

**Comment by paperjack93** [comment]
I'll make a test version modifying nox_client_makePlayerStatsDlg_463880 and send it to him
