### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by SilentMRG** [opennox/opennox#583]
Hello...

I copy and paste the files in the root directory, run "opennox.exe" and get a window that quickly opens and closes. No error message and no process open in task manager.

What am I missing?

I'm using a Laptop with an i5 2.67GHz, 4GB of memory and Windows 7 Ultimate 64bit with an Intel HD Graphics. The game runs great with this setup when I used cnc-ddraw to play two years ago.

Thanks in advance!

**Comment by dennwc** [comment]
Can you please upload a file `logs/opennox.log`?

**Comment by SilentMRG** [comment]
I would have done this if a log was created. There is no log or anything other than a window that opens and closes quickly.

**Comment by Evengard** [comment]
Did you try to run with admin permissions? Just to check if it is a permission issue.

**Comment by SilentMRG** [comment]
> Did you try to run with admin permissions? Just to check if it is a permission issue.

Yes, I ran it as an administrator and even disabled the antivirus, because sometimes it could be the antivirus blocking something.

Which backend does OpenNox use? Intel HD Graphics supports DX10 and OpenGL 3.0. Sometimes the "problem" is the non-compatible backend.

**Comment by Evengard** [comment]
We're using OpenGL 2.x (can't remember the exact version, but definitely not higher than OpenGL 3)

**Comment by SilentMRG** [comment]
Hmm... So this error is a mystery. I've never seen anything like it. Are you using any specific version of Visual Studio? I tried running "opennox.exe" again and no log was created. I also tried to run the executable in HD and neither the window that opens and closes quickly appeared, no log, or process in the task manager. Really, weird...

**Comment by vvs-** [comment]
From the readme:
> cnc-ddraw does not support Direct3D/Glide, it will only work with games that use a DirectDraw (Software) renderer.

That reminds me of the recent discussion in #573

**Comment by Evengard** [comment]
Nah, looks like something different. Maybe some dlls missing and failing to init or smth.

**Comment by SilentMRG** [comment]
> From the readme:
> 
> > cnc-ddraw does not support Direct3D/Glide, it will only work with games that use a DirectDraw (Software) renderer.
> 
> That reminds me of the recent discussion in #573

I can run Nox with cnc-ddraw in its latest version without problems. I just tried the OpenNox installation file and I have the same problems... It's a shame...

**Comment by SilentMRG** [comment]
> Nah, looks like something different. Maybe some dlls missing and failing to init or smth.

Could be... But what exactly? The game doesn't even create a log. It's laughing so as not to cry. XD

**Comment by vvs-** [comment]
> Nah, looks like something different. Maybe some dlls missing and failing to init or smth.

That's what I mean, if you would think about dlls in e.g. graphics driver. Nobody actually checked that it works.

> I can run Nox with cnc-ddraw in its latest version without problems. I just tried the OpenNox installation file and I have the same problems... It's a shame...

If you mean original Nox from Westwood then I should remind again that it does _not_ use Direct3D. But opennox does (only OpenGL).

For lack of a better option I would check everything I could. What if there is a problem in graphics driver installation? Also, I would try it on another computer to verify that those files are not corrupted and there is no other non-obvious mistake.

**Comment by SilentMRG** [comment]
> If you mean original Nox from Westwood then I should remind again that it does _not_ use Direct3D. But opennox does (only OpenGL).
> 
> For lack of a better option I would check everything I could. What if there is a problem in graphics driver installation? Also, I would try it on another computer to verify that those files are not corrupted and there is no other non-obvious mistake.

The Nox I play was purchased from GOG. And I'm using cnc-ddraw precisely because Nox (original) works in Ddraw. Yes, I know... That's why I asked which backend OpenNox uses, and according to Evengard it uses OpenGL 2.x, and Intel HD Graphics, as I said above has support for DX10 and OpenGL 3.0. Drivers are up to date. All the games I have here work and when they don't at least show an error message, something OpenNox refuses to do.

**Comment by vvs-** [comment]
> All the games I have here work and when they don't at least show an error message, something OpenNox refuses to do.

You didn't say which games are working there. If there are 32-bit ones _and_ they also use OpenGL _then_ it should be fine. Also, there is a small probability that there is a bug or incompatibility in graphics driver itself, e.g. Arabian Nights is a good example which works depending on moon's phase. In such cases there's often just a black screen or nothing at all. BTW, why not launch opennox from command line prompt? I know, it's Windows but it still might output some error...

**Comment by dennwc** [comment]
If no logs are created, try running it from `cmd.exe`. It should then show the logs in the console at least.

In general, if you see a window quickly appearing and then closing, OpenNox definitely runs. So it's not an issue with libraries. Could be drivers, or something with game data.

In any case, we need to see logs to be sure.

**Comment by dennwc** [comment]
Alternatively, you could try one of the recent [alpha releases](https://github.com/noxworld-dev/opennox/releases).

**Comment by SilentMRG** [comment]
After a lot of trying behold, a log appears...

2023/03/22 19:07:01 [version]: version: v1.8.11()
2023/03/22 19:07:01 [version]: GET https://ghcr.io/token?scope=repository%3Anoxworld-dev%2Fopennox%3Apull
2023/03/22 19:07:02 [config]: file not found, using defaults
2023/03/22 19:07:02 [registry]: install path at SOFTWARE\WOW6432Node\Westwood\Nox\InstallPath: "D:\\Westwood Studios - Nox\\Nox\\Nox.EXE"
2023/03/22 19:07:02 [registry]: install path at SOFTWARE\Westwood\Nox\InstallPath: "D:\\Westwood Studios - Nox\\Nox\\Nox.EXE"
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\WOW6432Node\\Westwood Studios\\NOX": The system cannot find the file specified.
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\Westwood Studios\\NOX": The system cannot find the file specified.
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\WOW6432Node\\GOG.com\\Games\\1207658964": The system cannot find the file specified.
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\WOW6432Node\\GOG.com\\Games\\1207658964": The system cannot find the file specified.
2023/03/22 19:07:02 [gog]: install path at SOFTWARE\WOW6432Node\GOG.com\GOGNOX\PATH: "D:\\Westwood Studios - Nox\\Nox\\"
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\WOW6432Node\\GOG.com\\GalaxyClient\\paths": The system cannot find the file specified.
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\GOG.com\\Games\\1207658964": The system cannot find the file specified.
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\GOG.com\\Games\\1207658964": The system cannot find the file specified.
2023/03/22 19:07:02 [gog]: install path at SOFTWARE\GOG.com\GOGNOX\PATH: "D:\\Westwood Studios - Nox\\Nox\\"
2023/03/22 19:07:02 [registry]: error opening key "SOFTWARE\\GOG.com\\GalaxyClient\\paths": The system cannot find the file specified.
2023/03/22 19:07:02 [path]: setting data dir to: "C:\\Users\\Downloads\\Nox"
2023/03/22 19:07:02 [config]: writing to "C:\\Users\\Downloads\\Nox\\opennox.yml"
2023/03/22 19:07:03 [version]: GET https://ghcr.io/v2/noxworld-dev/opennox/tags/list
2023/03/22 19:07:03 [version]: latest on github: v1.8.12-alpha4
2023/03/22 19:07:04 [sdl]: window size: 640x480
2023/03/22 19:07:04 [config]: writing to "C:\\Users\\Downloads\\Nox\\opennox.yml"

I just want to make two things clear:

Yesterday I installed the game on the D drive and I had the aforementioned problem. Today I installed it on the C drive in a rather unlikely folder (Downloads). As you can see in the log on both drives C and D the problem is apparently the same.

The second thing is that I downloaded the latest stable version, and not the one in the log (v1.8.12-alpha4) I didn't even download that version and the log showed it, I don't know why.

**Comment by SilentMRG** [comment]
Another point of interest:

2023/03/22 19:29:08 [version]: version: v1.8.11()
2023/03/22 19:29:08 [version]: GET https://ghcr.io/token?scope=repository%3Anoxworld-dev%2Fopennox%3Apull
2023/03/22 19:29:08 [config]: using file: "C:\\Users\\Downloads\\Nox\\opennox.yml"
2023/03/22 19:29:08 [path]: setting data dir to: "C:\\Users\\Downloads\\Nox"
2023/03/22 19:29:08 [config]: writing to "C:\\Users\\Downloads\\Nox\\opennox.yml"
2023/03/22 19:29:10 [version]: GET https://ghcr.io/v2/noxworld-dev/opennox/tags/list
2023/03/22 19:29:11 [version]: latest on github: v1.8.12-alpha4
2023/03/22 19:29:12 [sdl]: window size: 640x480
2023/03/22 19:29:12 [config]: writing to "C:\\Users\\Downloads\\Nox\\opennox.yml"

The other log was generated after I ran the opennox shortcut, the one above was generated after I ran opennox directly from the directory. Note that this log does not mention any errors. The HD executable generates the same log in both cases. Strange...

**Comment by Evengard** [comment]
This looks like opennox can't find your Nox install, the original resource files. You can't run opennox without them, as we're legally bound to not redistribute those.
Install original Nox through an installer and it should work.

**Comment by SilentMRG** [comment]
It makes no sense. I have Nox installed. GOG version.

See the pictures...

![0](https://user-images.githubusercontent.com/62117728/227055898-a397a16a-8abb-4f45-be1e-eaef455ca4b7.png)
![1](https://user-images.githubusercontent.com/62117728/227055923-bca134a4-42ef-47cf-ba1d-b2d04f09b0b7.png)
![2](https://user-images.githubusercontent.com/62117728/227055948-4657cf59-66aa-4200-be27-72ccb8477d86.png)

All the resources are there.

**Comment by Evengard** [comment]
> C:\Users\Downloads\Nox\opennox.yml

Do you have this file? Could you post it's contents?

**Comment by SilentMRG** [comment]
Of course...

Here goes...

extensions:
  spells:
    manual_cast:
      timeout: 0.5
game:
  data: .
  extensions:
    solo_allow_emotes: true
network:
  lobby:
    address: http://nox.nwca.xyz:8088
  port_forward: true
  xor: true
  xwis:
    register: true
server:
  api_token: ""
  control:
    allow_cmds: false
    allow_map_change: false
video:
  filtering: true
  gamma: 1
  size:
    height: 768
    width: 1024
  stretch: false

I opened it with a text editor. Did I do it right?

**Comment by Evengard** [comment]
Change that line:

> data: .

To

> data: C:\path\to\your\nox\files

Replace C:\path\to\your\nox\files with the actual path to your Nox directory.

Make sure to not alter the padding!

**Comment by Evengard** [comment]
We really should document this in the readme...

**Comment by SilentMRG** [comment]
Let me get this straight... you want me to put the program path in front of "C:\path\to\your\nox\files"?

Or put the program path in front of "data: ."?

I'm kind of new to these things, sorry.

So it would look like this:

"data: C:\Users\Downloads\Nox"

Correct?

**Comment by Evengard** [comment]
yep, you are correct. Maybe the problem is different, then... Weird, seems like you're doing it correctly. You didn't change the padding?

**Comment by SilentMRG** [comment]
Change padding? I don't even know what that is. I didn't mess with any files.

How do I save the file in .yml?

**Comment by SilentMRG** [comment]
I managed to convert the file and I did what you said, but the error persists.

If it helps, here it is:

extensions:
  spells:
    manual_cast:
      timeout: 0.5
game:
  data: C:\Users\Downloads\Nox
  extensions:
    solo_allow_emotes: true
network:
  lobby:
    address: http://nox.nwca.xyz:8088
  port_forward: true
  xor: true
  xwis:
    register: true
server:
  api_token: ""
  control:
    allow_cmds: false
    allow_map_change: false
video:
  filtering: true
  gamma: 1
  size:
    height: 768
    width: 1024
  stretch: false

I won't even post the log because the same one from the other post was generated. Seriously, I've never seen an error like this.

**Comment by Evengard** [comment]
Honestly, I'm at a loss. Only thing I can think off is debugging remotely over remote controlling software.

**Comment by SilentMRG** [comment]
Maybe it's some kind of curse. Sometimes Hecubah is in the realm of Nox doing some kind of spell that prevents me from running opennox. XD

Think... Sometimes she is not happy to know that Nox became open Nox, hehehe.

**Comment by dennwc** [comment]
Looking at [this log](https://github.com/noxworld-dev/opennox/issues/583#issuecomment-1480336114), it cut exactly after writing a config. This usually means it crashes after that point (either on audio or video init).

@SilentMRG Did you manage to run via `cmd.exe`?

**Comment by SilentMRG** [comment]
Yes, running through cmd results in the log already posted. Nothing new, unfortunately.

**Comment by dennwc** [comment]
Hmm, okay, then we'll need to produce a Windows debug build which will show the console when OpenNox starts. I'll do it this weekend.

**Comment by vvs-** [comment]
I've just compiled it from source code on Linux. It definitely doesn't run on OpenGL 2.1 and GLSL 1.20. I was able to run it only on OpenGL 3.3 and GLSL 1.50.

**Comment by SilentMRG** [comment]
That's what I thought... That's why I asked which backend he used. My laptop's Intel HD Graphics support OpenGL 3.0, opennox doesn't run due to backend incompatibility, if opennox requires OpenGL 3.3, so then the problem is on my side.

I would not have opened this issue if this information had been documented in the readme.

**Comment by Evengard** [comment]
Probably my fault. For some reason I thought it is OpenGL 2.3, not 3.3. Indeed, found that we refer OpenGL 3.3

**Comment by SilentMRG** [comment]
Don't worry... These things happen. =)

**Comment by SilentMRG** [comment]
So I'm closing this issue due to backend incompatibility. As previously said, the problem is not opennox, but the integrated card of my Laptop. Thank you all for your help and patience!

**Comment by Evengard** [comment]
As a possible workaround, you might try actually compile Mesa on your PC and try to run through that. Altough we never tested that, but Mesa have a high chance of helping you.

**Comment by Evengard** [comment]
If you're on Windows, you can try that: https://github.com/pal1000/mesa-dist-win#installation-and-usage

**Comment by vvs-** [comment]
Better yet I've slightly changed the shaders to make them GLSL 1.20 compatible. Mesa won't allow you to run unchanged shaders on GPU, so no hardware acceleration possible otherwise.
