### ISSUE TITLE
Bombers turn into traps on death when setting their spells, instead of properly exploding. 

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#585]
```go
ns.AsObj(con.bomber1).TrapSpells(spell.POISON, spell.FIST, spell.STUN)
con.bomber1.TrapSpells(spell.POISON, spell.FIST, spell.STUN)
```

**Comment by dennwc** [comment]
Cannot confirm this, spells appear to work fine when I test them separately. Maybe something else in the script causes this? For example, [this line](https://github.com/Ephreaym/Nox-AI-script/blob/252ef63314c34ac750eac1821ce921092ea1131e/conjurer.go#LL692C1-L692C23) that deletes the bomb?

**Comment by Ephreaym** [comment]
100% correct on the delete line.
