### ISSUE TITLE
NPC's need speed and strength modifier. 

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#588]
Need a function to change speed and strength.
This will allow the warbot to hit for the proper amount and allow to slow down the wiz/con/ speed up the war.

**Comment by dennwc** [comment]
I changed description to focus on speed and strength (since they are similar). @Ephreaym can you please create a separate issue for changing teams?

Related to https://github.com/Ephreaym/Nox-AI-script/issues/6

**Comment by dennwc** [comment]
Done, see new functions `SetBaseSpeed` and `SetStrength` for [Obj](https://pkg.go.dev/github.com/noxworld-dev/noxscript/ns/v4#Obj). Will be in the next alpha.
