### ISSUE TITLE
Game crash when loading a new map and another player is in the server

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#591]
Loading a new map works fine when alone. But when somebody joins the server loading a new map results in a crash.

Would be a nice priority fix since it’s demotivating for players.

**Comment by Poomex** [comment]
Can confirm, had multiple crashes of my server while playing in quest mode. It always kicks all players and switches to another map. Players cannot join again and it needs to be restarted. Here's the log.
[opennox-server.log](https://github.com/noxworld-dev/opennox/files/11390124/opennox-server.log)

**Comment by dennwc** [comment]
I currently reliably hit a variation of this where joining the chat lobby game works, but then switching the map just freezes the server. Bisected to a97a41aa3383caf05690c96b22fdc0691e09b616, specifically in `nox_xxx_spriteDeleteAll_45A5E0` or `nox_xxx_spriteIsPlayerSprite_45A630`. Still figuring out what's wrong. If it's the same bug, it started from `v1.8.12-alpha2`.

**Comment by dennwc** [comment]
Fixed. It will be in the next alpha.
