### ISSUE TITLE
Saved game fails to load

### ISSUE THREAD

**Issue by raptorswing** [opennox/opennox#593]
I've been playing through the Warrior campaign in OpenNox 1.8.11. But now the game fails to load my save, and unfortunately I have only one, so I guess my progress may be lost.

I've attached [opennox.log](https://github.com/noxworld-dev/opennox/files/11861184/opennox.log) and my 
[Save folder](https://github.com/noxworld-dev/opennox/files/11861202/Save.zip). I hope those could be helpful in reproducing the issue.

**Comment by dennwc** [comment]
Could you please try one of the [latest alpha builds](https://github.com/noxworld-dev/opennox/releases)? Another way to try to recover the save is to load and save it with vanilla. It was reported that it also helps.

**Comment by raptorswing** [comment]
Yes, I just tried it in 1.8.12-alpha7 and it worked fine. 👍 

Also, good tip about loading in vanilla and making a new save. That worked, too.

Closing this since it seems the issue is already fixed in newer builds.
