### ISSUE TITLE
Game crash when thrown weapon is used on a NPC (and maybe player?)

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#595]
The game crashes when a thrown weapon is used on a NPC (maybe also on a player?). This includes the shuriken (also when thrown from an ogre lord) and the chackrum.

**Comment by dennwc** [comment]
Happens every time a throwable projectile hits something. Bisected to d37a716a19a318d895ff26255862d5785412ef0e.

**Comment by dennwc** [comment]
Fixed. Will be in the next alpha.
