### ISSUE TITLE
Sight range function added for NPC.

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#598]
A sight range function would be very welcome to improve the ability of the bots. It's probably similar to the speed and strength fix.

**Comment by Ephreaym** [comment]
Wouldn't mind an early update on this. :) Would improve the con and warriors a lot. Since now they're standing still listening more often while in range of enemy players.

**Comment by dennwc** [comment]
No updates for now, except that I did refactor AI system a bit. Could check how to remove/change this sight restriction.

**Comment by dennwc** [comment]
Whole AI pathfinding was ported, and there was some progress on the AI actions as well. Hopefully it should be possible to port the "is enemy visible" AI check next, so that we could customize it whatever we want.

**Comment by Ephreaym** [comment]
Not sure if it translates. But sight range is already adjustable in the mapeditor when you customize an NPC.

**Comment by dennwc** [comment]
That's definitely helpful :+1:

**Comment by Ephreaym** [comment]
Not sure if it’s more easy to implement instead of adding a new function. But maybe we could change the default sight range when a new npc is added with the createobject function to 500?

**Comment by dennwc** [comment]
Here's a test map with two NPCs: one with a default sight range of 150, and the second one with custom range of 123. Will use it to debug the code and find how the sight range is set for NPCs.

[rangetest.zip](https://github.com/user-attachments/files/17611123/rangetest.zip)

**Comment by dennwc** [comment]
Added in eaf57c84e6ed22c418b64898f8dd3b2f8d5dc400
