### ISSUE TITLE
Equip function seems to have a cap

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#599]
Put a NPC in a room with all items and run equip. It'll only pick-up a couple of them. There seems to be a cap integrated with equip?

**Comment by Ephreaym** [comment]
https://youtu.be/t3gzW2hhCUw

```go
func findLootRedBot() {
	const dist = 75
	// Melee weapons.
	armor := ns.FindAllObjects(
		ns.InCirclef{Center: RedBot, R: dist},
		ns.HasClass(object.ClassArmor),
		//ns.HasClass(object.ClassWeapon),
	)
	if armor != nil {
		//RedBot.Pickup(item[0])
		RedBot.Equip(armor[0])
	}

	weapon := ns.FindAllObjects(
		ns.InCirclef{Center: RedBot, R: dist},
		//ns.HasClass(object.ClassArmor),
		ns.HasClass(object.ClassWeapon),
	)
	if weapon != nil {
		//RedBot.Pickup(item[0])
		RedBot.Equip(weapon[0])
	}

	ns.NewTimer(ns.Frames(15), func() {
		findLootRedBot()
	})
}
```
[test equip cap.zip](https://github.com/noxworld-dev/opennox/files/14001621/test.equip.cap.zip)

**Comment by Ephreaym** [comment]
Here's the video that demonstrates the weird cap. I haven't found out the conditions exactly. But there's something limiting the amount of items that can be equipped and picked up.

**Comment by dennwc** [comment]
Another test map to demonstrate the issue

[itembug (2).zip](https://github.com/user-attachments/files/18149727/itembug.2.zip)
