### ISSUE TITLE
Obliteration does no damage

### ISSUE THREAD

**Issue by dennwc** [opennox/opennox#607]
Obliteration does no damage even when cast with full mana. The effect plays, but no damage to ether the caster or the surrounding.

**Comment by rgarrett15** [comment]
Ye

**Comment by al0fdf** [comment]
After a while of using `git bisect`: 
> 8560f4f8b340de031b8e2a84a99c6c13b18c438a is the first bad commit

**Comment by dennwc** [comment]
Thank you a lot! I think I even see what the problem is:
https://github.com/noxworld-dev/opennox/commit/8560f4f8b340de031b8e2a84a99c6c13b18c438a#diff-bb087cd9cea2bb66f5174686510f3819937c8c16f205747666199c169c85e69eR1771
It should `return true`, obviously :man_facepalming:

If you have time, could you check if it works that way?

**Comment by al0fdf** [comment]
> Thank you a lot! I think I even see what the problem is: [8560f4f#diff-bb087cd9cea2bb66f5174686510f3819937c8c16f205747666199c169c85e69eR1771](https://github.com/noxworld-dev/opennox/commit/8560f4f8b340de031b8e2a84a99c6c13b18c438a#diff-bb087cd9cea2bb66f5174686510f3819937c8c16f205747666199c169c85e69eR1771) It should `return true`, obviously 🤦‍♂️
> 
> If you have time, could you check if it works that way?

Obliteration deals damage again with `return true`. I've created https://github.com/noxworld-dev/opennox/pull/642
