### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by ghost** [opennox/opennox#630]
https://mega.nz/file/WppyFQgK#A3a7UQYQ8etwIYAzmW1dB-X_qTd0p6smIelvh45Zpxw

Hello friends, I'm leaving the file here to change Nox to Spanish.

Great job with OpenNox!! Thank you.

**Comment by dennwc** [comment]
Thank you as well for the translation file! For now we will only store it for the future.

The idea is to use [our Crowdin page](https://crowdin.com/project/opennox) for translation. We already uploaded the translations we are aware of, and Spanish version there looks very similar to the file you shared.

I opened a separate ticket to track translation support: https://github.com/noxworld-dev/opennox/issues/631.
