### ISSUE TITLE
NS4: Add "pure" damage type

### ISSUE THREAD

**Issue by dennwc** [opennox/opennox#637]
Currently scripts may set any existing damage type, but sometimes it's not enough. Each damage type has its own specifics, while for scripts you sometimes just want to deal specific damage that ignores all armor, resists, etc.

There's a function that deals this damage type: `nox_xxx_unitDamageClear_4EE5E0`. It's used for Channel Life spell, Elimination's Sudden Death, etc.

I think we could expose it as a special damage type: `PURE = -1`. It's only relevant to scripts, so we will just switch on that type and run a different function.

**Comment by KILAH4716** [comment]
I'm about to test damage types to see if any kind of damage can already be identified as "pure" damage.

**Comment by Evengard** [comment]
In other games that kind of damage is usually called "true damage", btw.
