### ISSUE TITLE
Missiles of Magic has misaligned particle effects

### ISSUE THREAD

**Issue by comradeshook** [opennox/opennox#653]
![noxbug](https://github.com/noxworld-dev/opennox/assets/8018945/0ef8c6fa-72c7-4ccf-9fa9-02bb30bbf35f)

The particles emitted by Missiles of Magic seem to be vertically misaligned with the projectile. It's a bit hard to tell, but i think the same issue is present with the initial burst of particles when casting Lightning; i believe it normally originates from your feet, but here it originates from around head height. As i'm not yet further in the game (on this project), i don't know if this happens for other spells, but the projectile for Lesser Heal seems to look normal.

This is on Windows, playing v1.9.0-alpha12, with me having the GOG version of Nox installed.

**Comment by dennwc** [comment]
Confirmed, it is a regression in the latest version. Will fix before the stable release :+1:
