### ISSUE TITLE
Game hard crashes when hovering over certain normally-inaccessible items

### ISSUE THREAD

**Issue by comradeshook** [opennox/opennox#655]
This is _very_ unlikely to ever affect normal gameplay, but when you use cheats to spawn certain items (e.g. `DemonsBreathWand` and `MissileWand`), they cause a hard crash when you hover over them for long enough to display their names. As a side note, quick hands and `cheat equip.all` let you find out that `DemonsBreathWand` actually sorta works, but this is not the case for the other staves, sadly.

Disclaimer, i do not currently know if this also happens in the base game, as i can't play it directly. 
Running on Windows, GOG version, v0.1.9 alpha12.

**Comment by dennwc** [comment]
Thank you for reporting it! Should be easy to fix.

As for the wands, we need to check if they have any useful code remaining.
