### ISSUE TITLE
Archer on the route to Stravas misses his shot on the explosive barrel

### ISSUE THREAD

**Issue by comradeshook** [opennox/opennox#658]
![nox3](https://github.com/noxworld-dev/opennox/assets/8018945/597e5180-df80-4146-ad59-81978b50d957)

As per title, this annoying asshole misses his initial shot intended to detonate the barrel in this room. Possibly related to #657 ?

Playing on Windows, GOG version, v1.9.0 alpha12.

**Comment by Evengard** [comment]
Offtop: I actually remember fixing that bug when it was C only, the guy was shooting in a completely wrong direction. Was something to do with float calculations... Maybe Go skewed that again somehow.

Kinda a regression! xD

**Comment by dennwc** [comment]
I think this time it's different. This archer was only a bit off probably, similar to #657.

**Comment by comradeshook** [comment]
If memory serves, he did shoot in a north-ish direction, so that would check out. I say the following without knowing how things actually work, but perhaps something to do with scripted targeting? They're all unerringly accurate when playing normally, it's only these scripted sequences that bug out.

**Comment by Evengard** [comment]
Wait, what? North? That's exactly the same way the bug in C behaved, iirc

**Comment by Evengard** [comment]
https://github.com/noxworld-dev/opennox/commit/555eba598269414b0e3bedba98a6e12cc445b9a2
Check that commit @dennwc, may be related

**Comment by dennwc** [comment]
Haven't checked yet, but here's the commit porting that function: 122875acd0fbf77f27697fa804fe3f395541af10

**Comment by Evengard** [comment]
At the very least looks like types are wrong, uint32t instead of floats

**Comment by dennwc** [comment]
Fixed via https://github.com/noxworld-dev/opennox/commit/a0bb1dcd072854100c05174a36b90aff1b53ef46 :man_facepalming: I hate C pointer rules :sweat_smile:

**Comment by comradeshook** [comment]
Oh right by the way @dennwc, would this also fix monsters not turning towards you when they hear you? Otherwise i got another issue to add and document :V
I'm wondering because they were all steadfastly turned north, much like how the archer and urchins fired north, so maybe the issues are/were related.

**Comment by dennwc** [comment]
No, the one I fixed only affects scripted monsters firing. Can you please open a new ticket for this?

**Comment by comradeshook** [comment]
Yep yep, coming right up. Just need to secure a good repro. :v

**Comment by comradeshook** [comment]
Hmm, in retrospect, i think it might actually be #512 that i ran into, enemies did turn around like they should when i fell down after the necromancer in Field of Valor. I'll keep an eye out though, in case i run into something similar again.
