### ISSUE TITLE
Loose objects open containers on contact

### ISSUE THREAD

**Issue by comradeshook** [opennox/opennox#659]
![noxbugloosethings](https://github.com/noxworld-dev/opennox/assets/8018945/1480a4a0-8cc9-4a8b-b0b8-0cd225bc028e)

Loose objects, e.g. broken wall debris, makes containers open on contact. I noticed it once before in the room with the archer and explosives, but that was off screen; here, it first happened when i busted down the wall and then the sarcophagus opened on its own, but i was able to reproduce it by using Push.

Playing on Windows, GOG version, v1.9.0 alpha12.

**Comment by comradeshook** [comment]
On a similar note, loose objects also trigger (your) wizard traps, not sure if that's intended behaviour.

**Comment by comradeshook** [comment]
Additional note, enemies can also open containers by bumping into them, likely the same issue.

**Comment by dennwc** [comment]
> On a similar note, loose objects also trigger (your) wizard traps, not sure if that's intended behaviour.

It's supposed to be that way, I think. But not for chests!

> Additional note, enemies can also open containers by bumping into them, likely the same issue.

Not sure if it's the same in vanilla or not :thinking:

**Comment by comradeshook** [comment]
> > On a similar note, loose objects also trigger (your) wizard traps, not sure if that's intended behaviour.
> 
> It's supposed to be that way, I think. But not for chests!

That makes sense, i think it's neat anyways that you can abuse physics to trigger traps without having to step on them. :v


> > Additional note, enemies can also open containers by bumping into them, likely the same issue.
> 
> Not sure if it's the same in vanilla or not 🤔

Can't quite remember either, but it felt unusual when it happened, so i _think_ it's a new thing. I'll try and see if there's an easy way for me to get to Tombs of Valor on Nox Reloaded, it's a bit of a hassle to play all the way to chapter 4 for a small bug that might not even be a bug. 😅
Hardly a game breaking issue in any case, i haven't yet encountered a situation where it made anything unfair or unplayable.

**Comment by Evengard** [comment]
Saves should be backward compatible, you can try open a save made in OpenNox in vanilla, should work.

**Comment by comradeshook** [comment]
Nice; i was unfortunately not smart enough to not overwrite the save as i moved along, but i'll keep it in mind if i end up replaying. It's at least a thing that's independent of class. :v

**Comment by comradeshook** [comment]
> > Additional note, enemies can also open containers by bumping into them, likely the same issue.
> 
> Not sure if it's the same in vanilla or not 🤔

Confirmed (and recorded, once i've processed the video) that this _doesn't_ happen in vanilla.

**Comment by dennwc** [comment]
Bisected to 5da20d42abaee328dd9c8360f79251b8a58ef1e0 in `nox_xxx_collideChest_4E9C40`

**Comment by dennwc** [comment]
Found it:
```c
if (*(uint8_t*)(a2 + 8) & 4 == 0) {
```
->
```c
if ((*(uint8_t*)(a2 + 8) & 4) == 0) {
```

**Comment by dennwc** [comment]
Fixed in `dev`. Will be in the next alpha release.

@comradeshook thank you for reporting all these issues!

**Comment by comradeshook** [comment]
No problem! Of course it was the classic missing parentheses, nicely found :V
