### ISSUE TITLE
Game saves aren't working in OpenNox

### ISSUE THREAD

**Issue by bradmillar** [opennox/opennox#690]
Hi guys. Great work on this. The game actually runs now and incredibly well. However, I cannot get saved games to load. The load menu is non responsive. I can select a prior save, but then the confirm button doesn't work. Have tried the latest version as of this date, plus your alpha version and nada...

Any ideas? Installation is from EA app on Windows 11. Thanks!

**Comment by bradmillar** [comment]
Ok think I have resolved it. Uninstalled the game and opennox. Reinstalled the game from EA app but into a folder on root C:/ and not into the default c:/program files/. Redownloaded opennox. All good. Game saves load now. Maybe it was a permission/rights issue?

**Comment by dennwc** [comment]
Yes, it could be. I think I've heard about similar issues before. Glad it works now!

**Comment by angrykirc** [comment]
In case someone also stumbles upon similar issue, please attach the log from the "./logs/opennox.log" file.
