### ISSUE TITLE
Sparks are rendered too high

### ISSUE THREAD

**Issue by angrykirc** [opennox/opennox#710]
The screenshot should be self expanatory.
There is some kind of fixed offset to *SparkDraw that sets them floating too high from the floor
![nox5](https://github.com/user-attachments/assets/43e04a76-f895-4bf8-a855-a1399d8a4465)

**Comment by dennwc** [comment]
@angrykirc are you sure it's not fixed by https://github.com/noxworld-dev/opennox/commit/eb7c49a4fde0690ca9e65a08a5da5268b959c351 ?

**Comment by angrykirc** [comment]
@dennwc It is fixed, indeed. Thank you for pointing me :)
