### ISSUE TITLE
No sound in linux (GoG version)

### ISSUE THREAD

**Issue by FlaubertNHR** [opennox/opennox#712]
Version v1.09-alpha13 of open NOX (Ubuntu 22.04, Jammy)
Assets from NOX2.0.0.20 (GoG).
Just copied openNOX to game folder and started with either opennox or opennox-hd. All works, but no sound & music.

Perhaps sound assets from GOG version are in other folder than expected?

**Comment by blmarket** [comment]
Did you see intro video? (like Jack being summoned etc.)

If no - likely the game couldn't find the assets properly. Stop this flowchart.

Did the sound played properly with the video?

If yes - likely the game couldn't find the audio assets properly. Stop this flowchart.

If no - likely the game couldn't find the audio driver to play audio stuff. AFAIK the game uses OpenAL for audio driver. You may need to check ubuntu package libopenal is installed (there could be more packages to check)

**Comment by FlaubertNHR** [comment]
My bad!!! all sound sliders were at lowest position(0)!!! And "sounds" and "voice" were deactivated!!
So, problem solved. Perhaps they didn't have to start in those states when doing a new install.
Thanks a lot!!
