### ISSUE TITLE
Request: Load specific map through ns4 for quest. 

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#720]

**Comment by Ephreaym** [comment]
To be fair: allowing us to set the map through exit objects would also be very helpful. Because that way I can use those objects without having to work around them. Not sure how hard that is to implement, though?

For example:

![image](https://github.com/user-attachments/assets/fd6b947e-1d10-4a10-ae7d-549aaeff4e64)

**Comment by Ephreaym** [comment]
Right now it loads a random quest map (goes for all exit objects).

**Comment by dennwc** [comment]
@Ephreaym could you please open a separate ticket for fixing the exit nodes in quest? I'll close this issue as soon as `LoadMap` is added to NS4.

**Comment by dennwc** [comment]
Implemented in 03e4d26ee0e90aebb199db59c147e36049bc86a3
