### ISSUE TITLE
BUG: Quest server crashes when a player leaves the server.

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#728]
Happends on normal quest maps.

1.) I host a regular Quest game.
2.) A player joins.
3.) Player leaves.
4.) Game crashes and closes down.

**Comment by Ephreaym** [comment]
Hmm, seems to not happen consistently. I do get this message when a player leaves.

![image](https://github.com/user-attachments/assets/c4395ba5-a9c9-4099-a4ac-e449286a3bc1)

**Comment by Ephreaym** [comment]
Will need to investigate further. It happens consistently when I join my own server, but that might be another issue.

**Comment by dennwc** [comment]
I think I've seen something similar with this `.../save/save/...` path. It's definitely a bug.
