### ISSUE TITLE
FieldGuide issue: need a way to create/award a specific one.

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#729]
You can't award a specific FieldGuide object to a character or create one through NS4. I can cover it with granting you an existing item on the map, but that won't work for a persisting server.

Another option would be to allow a script to "copy" an existing item, but not sure if that's more easy/possible.

**Comment by dennwc** [comment]
Implemented in ebdbbfc4d5ea6b1b7a2e49d4037f37509a4af694 .
